.nh
.TH "ENVCTL" "1" "Dec 2025" "uRadical" "envctl manual"

.SH NAME
.PP
envctl-env-var - Manage environment variables via operations chain


.SH SYNOPSIS
.PP
\fBenvctl env var [flags]\fP


.SH DESCRIPTION
.PP
Manage environment variables using an append-only operations chain.

.PP
Variables are stored as signed operations, similar to git commits.
Each operation is hash-linked and cryptographically signed.

.PP
Unlike the traditional .env file approach, the operations chain:
- Provides a complete audit trail of all changes
- Enables conflict detection when syncing with peers
- Ensures integrity through cryptographic signatures
- Stores values encrypted to your own key

.PP
Examples:
  envctl env var set API_KEY "secret123"           # Set a variable in current env
  envctl env var set -e prod API_KEY "prodkey"    # Set in prod environment
  envctl env var get API_KEY                       # Get a variable
  envctl env var delete API_KEY                    # Delete a variable
  envctl env var list                              # List all variables
  envctl env var status                            # Show chain status
  envctl env var log                               # Show recent operations


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for var


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	config file (default $HOME/.config/envctl/config.toml)

.PP
\fB--lang\fP=""
	language for messages (default: auto-detect)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
.PP
\fBenvctl-env(1)\fP, \fBenvctl-env-var-delete(1)\fP, \fBenvctl-env-var-get(1)\fP, \fBenvctl-env-var-list(1)\fP, \fBenvctl-env-var-log(1)\fP, \fBenvctl-env-var-pull(1)\fP, \fBenvctl-env-var-push(1)\fP, \fBenvctl-env-var-set(1)\fP, \fBenvctl-env-var-status(1)\fP


.SH HISTORY
.PP
29-Dec-2025 Auto generated by spf13/cobra
