.nh
.TH "ENVCTL" "1" "Jan 2026" "uRadical" "envctl manual"

.SH NAME
.PP
envctl-project - Project management commands


.SH SYNOPSIS
.PP
\fBenvctl project [flags]\fP


.SH DESCRIPTION
.PP
Manage project membership and access.

.PP
Projects use a cryptographically signed blockchain to track membership.
All changes require approval from project members based on project policy.

.PP
The 'team' command is an alias for 'project'.


.SH OPTIONS
.PP
\fB-h\fP, \fB--help\fP[=false]
	help for project

.PP
\fB-p\fP, \fB--project\fP=""
	project name (overrides .envctl file)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--config\fP=""
	config file (default $HOME/.config/envctl/config.toml)

.PP
\fB--lang\fP=""
	language for messages (default: auto-detect)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
.PP
\fBenvctl(1)\fP, \fBenvctl-project-access(1)\fP, \fBenvctl-project-approve(1)\fP, \fBenvctl-project-create(1)\fP, \fBenvctl-project-delete(1)\fP, \fBenvctl-project-deny(1)\fP, \fBenvctl-project-dissolve(1)\fP, \fBenvctl-project-grant(1)\fP, \fBenvctl-project-invite(1)\fP, \fBenvctl-project-invites(1)\fP, \fBenvctl-project-join(1)\fP, \fBenvctl-project-leave(1)\fP, \fBenvctl-project-link(1)\fP, \fBenvctl-project-list(1)\fP, \fBenvctl-project-log(1)\fP, \fBenvctl-project-members(1)\fP, \fBenvctl-project-pending(1)\fP, \fBenvctl-project-relay(1)\fP, \fBenvctl-project-remove(1)\fP, \fBenvctl-project-revoke(1)\fP, \fBenvctl-project-revoke-invite(1)\fP, \fBenvctl-project-sync(1)\fP


.SH HISTORY
.PP
6-Jan-2026 Auto generated by spf13/cobra
