# golangci-lint configuration for envctl
# Run with: golangci-lint run

run:
  timeout: 5m
  go: "1.24"

linters:
  disable-all: true
  enable:
    # Security - critical for a secrets management tool
    - gosec          # Security-focused linter
    - bodyclose      # Checks HTTP response body is closed
    - noctx          # Finds http requests without context.Context

    # Bug detection
    - staticcheck    # Advanced static analysis
    - govet          # Official Go vet tool
    - errcheck       # Checks unchecked errors
    - ineffassign    # Detects unused variable assignments
    - typecheck      # Type checking

    # Code quality
    - gofumpt        # Stricter gofmt
    - goimports      # Manages imports
    - misspell       # Finds misspelled words
    - unconvert      # Removes unnecessary type conversions
    - unparam        # Finds unused function parameters
    - unused         # Finds unused code

    # Style and best practices
    - revive         # Replacement for golint
    - gocritic       # Comprehensive code quality checks
    - godot          # Checks comment periods
    - whitespace     # Detects leading/trailing whitespace

    # Error handling
    - errorlint      # Finds problems with error wrapping
    - wrapcheck      # Ensures errors from external packages are wrapped

linters-settings:
  gosec:
    severity: high
    confidence: high
    excludes:
      - G104  # Audit errors not checked (we use errcheck for this)
    config:
      G301: "0750"  # Directory permissions
      G302: "0600"  # File permissions
      G306: "0600"  # WriteFile permissions

  errcheck:
    check-blank: true
    check-type-assertions: true
    exclude-functions:
      - (io.Closer).Close
      - (net.Conn).Close

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too noisy, not worth the optimization

  staticcheck:
    checks: ["all"]

  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - whyNoLint
      - hugeParam  # Can be noisy with large structs

  gofumpt:
    extra-rules: true

  goimports:
    local-prefixes: envctl.dev/go/envctl

  misspell:
    locale: GB  # British English for uRadical (Ireland-based)

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithStack(
    ignorePackageGlobs:
      - envctl.dev/go/envctl/*

issues:
  exclude-use-default: false

  exclude-rules:
    # Test files can be more relaxed
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - wrapcheck

    # Main package can have simpler error handling
    - path: cmd/envctl/main\.go
      linters:
        - wrapcheck

    # Generated files
    - path: tools/gendocs/
      linters:
        - errcheck

  max-issues-per-linter: 50
  max-same-issues: 10

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
